# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 风过留痕
email: zhht1204@163.com
description: > # this means to ignore newlines until "baseurl:"
  中国，上海，周会闲。ACG爱好者。
baseurl: "" # the subpath of your site, e.g. /blog
url: "zhht1204.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# My settings
excerpt_separator: <!-- more -->
keywords: 编程,python,ACG,动漫,galgame
twitter_username:     zhht1204  # Replace this with your Twitter username
github_username:      zhht1204  # Replace this with your GitHub username
linkedin_username:      # Replace this with your LinkedIn username
google_plus_username: zhht1204@gmail.com  # Replace this with your Google+ username
facebook_username:    zhht1204  # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

paginate: 5

post_image_directory: "/images/posts"
image_directory: "/images"
css_directory: "/css"
js_directory: "/js"
